spring:
##################    JDBC 配置    ################
#数据库配置
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/etongdb?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: 123456
  ##################    连接池配置    ################
  #连接池建立时创建的初始化连接数
      initial-size: 5
  #连接池中最大的活跃连接数
      max-active: 20
  #连接池中最小的活跃连接数
      min-idle: 5
  # 配置获取连接等待超时的时间
      max-wait: 60000
  # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  #spring.datasource.druid.max-open-prepared-statements:  #和上面的等价
  #validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
  #是否在获得连接后检测其可用性
      test-on-borrow: false
  #是否在连接放回连接池后检测其可用性
      test-on-return: false
  #是否在连接空闲一段时间后检测其可用性
      test-while-idle: true
  #spring.datasource.druid.time-between-eviction-runs-millis: 
  #spring.datasource.druid.min-evictable-idle-time-millis: 
  #spring.datasource.druid.max-evictable-idle-time-millis: