spring:
  port: 8080
  profiles:
    active: dev
##########################  log   ##########################
logging:
  config: classpath:logback-spring.xml

##########################  mybatis   ##########################
#mapper.xml文件放置的位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
